version: '3'

services:
  postgresdb-compose:
    env_file:
      - .env
    image: postgres
    container_name: db-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    env_file:
      - .env
    image: dpage/pgadmin4
    container_name: pgadmin-4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - postgresdb-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
